version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - backend_network

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network

volumes:
  redis_data:

networks:
  backend_network:
